name: List Application Gateways

on:
    workflow_dispatch:
    push:
    #     branches:
    #         - main

jobs:
    list-gateways:
        runs-on: ubuntu-latest
        steps:
        - name: Set up Azure CLI
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: List Application Gateways
          run: |
            az network application-gateway list --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --query '[].{Name:name, ResourceGroup:resourceGroup}' -o table

        - name: List Backend Pool Names
          run: |
            gateways=$(az network application-gateway list --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --query '[].name' -o tsv)
            for gateway in $gateways; do
                echo "Backend Pool Names for $gateway:"
                #resource_group=$(az network application-gateway show --name $gateway --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --query 'resourceGroup' -o tsv)
                #az network application-gateway show --name $gateway --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --query 'backendAddressPools[].name' -o tsv
                echo
            done