name: List Application Gateways

on:
    push:
        branches:
            - main

jobs:
    list-gateways:
        runs-on: ubuntu-latest

        steps:
            - name: Set up Azure CLI
                uses: azure/login@v1
                with:
                    creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: List Application Gateways
                run: |
                    az network application-gateway list --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"